Issue/2 fix selenium click on ubuntu
Roxe322/prpr pull request #4
Opened 2023-06-24 19:28 UTC by theoden-dd

The core commit is 16e2f4ef266bf8f6961421870b49827d948a8c7d .
I had success with it, but let me test it a bit more, I'll send a separate confirmation message later on.

In spite of that let's start the discussion right away.
Probably we need some changes in the readme file alongside etc.

2023-06-28 10:26 UTC, theoden-dd commented
The test was successful: met no more error reported.

2023-06-28 13:24 UTC, Roxe322 requested changes

2023-06-28 13:24 UTC, Roxe322 commented on .prpr-example.yaml
> +free_work_owner: lepervushina
let's change it please to robot-botlegger

2023-06-28 13:24 UTC, Roxe322 commented on prpr/download.py
> +        action.move_to_element(element).click().perform()
What should we do with old click on 214 line?

https://github.com/Roxe322/prpr/pull/4/files#diff-26d6c853b0b43523a5214cb00a6b0148c12c9fb41575b0605ec973e13bc0db46R214

2023-06-28 13:24 UTC, Roxe322 commented on prpr/download.py
> +        # The simple `element.click()` solution has stopped working on 19.05.2023.
Let's make this comment shorter or even remove it:

`simple element.click() doesn't work here for some reason`

2023-06-28 13:24 UTC, Roxe322 commented on .prpr-example.yaml
> +
What's the matter of renaming this config? should we change something about setup in readme then?

2023-07-05 09:13 UTC, Roxe322 approved these changes

2023-07-05 09:21 UTC, merged